# Generated by Django 5.2.2 on 2025-06-14 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calls", "0005_alter_calllog_npc_alter_calllog_recruit"),
    ]

    operations = [
        migrations.AddField(
            model_name="calllog",
            name="location",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="calls.location",
            ),
        ),
        migrations.AddField(
            model_name="mission",
            name="incorrect_text",
            field=models.TextField(
                blank=True,
                help_text="Given to the user when the get the code wrong",
            ),
        ),
    ]
