"""Generated by Django 5.2.2 on 2025-06-14 17:39."""

from typing import ClassVar

from django.db import migrations, models


class Migration(migrations.Migration):
    """Track if NPCs have been contacted."""

    dependencies: ClassVar = [
        ("calls", "0006_calllog_location_mission_incorrect_text"),
    ]

    operations: ClassVar = [
        migrations.AlterField(
            model_name="recruitnpc",
            name="contacted",
            field=models.BooleanField(default=False),
        ),
    ]
