# Generated by Django 5.2.2 on 2025-06-14 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0006_calllog_location_mission_incorrect_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitnpc',
            name='contacted',
            field=models.BooleanField(default=False),
        ),
    ]
