"""Generated by Django 5.2.2 on 2025-06-15 16:40."""

from typing import ClassVar

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """Track timing of missions."""

    dependencies: ClassVar = [
        ("calls", "0007_alter_recruitnpc_contacted"),
    ]

    operations: ClassVar = [
        migrations.AlterField(
            model_name="mission",
            name="call_back_from",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="calls.location",
            ),
        ),
        migrations.AlterField(
            model_name="recruitmission",
            name="finished",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="recruitmission",
            name="started",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
