"""Generated by Django 5.2.2 on 2025-06-22 14:09."""

from typing import ClassVar

from django.db import migrations, models


class Migration(migrations.Migration):
    """Track mission state."""

    dependencies: ClassVar = [
        ("calls", "0010_calllog_completed_calllog_success_and_more"),
    ]

    operations: ClassVar = [
        migrations.AddField(
            model_name="recruitmission",
            name="state",
            field=models.JSONField(default=dict),
        ),
    ]
