# Generated by Django 5.2.2 on 2025-06-22 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0011_recruitmission_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitmission',
            name='state',
            field=models.JSONField(null=True),
        ),
    ]
