"""Generated by Django 5.2.2 on 2025-06-22 17:24."""

from typing import ClassVar

from django.db import migrations, models


class Migration(migrations.Migration):
    """Track mission state for Lua."""

    dependencies: ClassVar = [
        ("calls", "0011_recruitmission_state"),
    ]

    operations: ClassVar = [
        migrations.AlterField(
            model_name="recruitmission",
            name="state",
            field=models.JSONField(null=True),
        ),
    ]
