"""Generated by Django 5.1.13 on 2025-10-13 16:59."""

from typing import ClassVar

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """Add details to call log."""

    dependencies: ClassVar = [
        ("calls", "0012_alter_recruitmission_state"),
    ]

    operations: ClassVar = [
        migrations.AlterField(
            model_name="calllog",
            name="NPC",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="calls.npc",
            ),
        ),
        migrations.AlterField(
            model_name="calllog",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="calls.location",
            ),
        ),
        migrations.AlterField(
            model_name="calllog",
            name="recruit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="calls.recruit",
            ),
        ),
        migrations.AlterField(
            model_name="recruitmission",
            name="state",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name="Speech",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("recording", models.FileField(upload_to="")),
                (
                    "NPC",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="calls.npc",
                    ),
                ),
            ],
        ),
    ]
