# Generated by Django 5.1.13 on 2025-10-22 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0013_alter_calllog_npc_alter_calllog_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='speech',
            name='tts',
            field=models.BooleanField(default=True),
        ),
    ]
