# Generated by Django 5.1.13 on 2025-12-05 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0014_speech_tts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruit',
            name='score',
        ),
        migrations.AddField(
            model_name='recruitnpc',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
